### PR TITLE
Add Timestamp Tracking

### PR DESCRIPTION
**Pull request by kirubarajan**
- Cleaned up some UI elements and code structure
- Timestamps are given by a comma-delimited list of UNIX timestamps in `annotate.html` JavaScript (`timestamps`).
- Timestamps are stored in the `Annotation` model as a `CharField`
- TODO: write utility to align timestamps with generations to perform analysis

### CODE REVIEW

**Comment by daphnei** [comment]
Just wondering, is there a reason to store the timestamps as CharField, rather than a list of DateTimeField?

The advantage of DateTimeField is that we can make temporal queries to it without needing to parse it. 

You could add something like:
```
class AnnotationTimeStamp(models.Model):
    # The annotation this time stamp is associated with
    annotation = models.ForeignKey(Annotation, on_delete=models.CASCADE)
    # The index of this time stamp for this annotation. We have multiple timestamps per annotation right?
    index = models.IntegerField()
   # The actual timestamp value?
    date = models.DateField(default=None, blank=False, null=False)

 ```

This would also save bad things from happening if the length of the timestamps goes over 256 characters (not sure how likely that would be with what you've currently implemented).

**Comment by kirubarajan** [comment]
That's a good idea, definitely is better practice to abstract into a ManyToMany relationship.

I'll refactor to a separate class that uses an IntegerField (the only data we need is # of seconds between continuations). Not sure if we'll need a full DateTime field since it seems unlikely to me that we'll be writing queries that require the date/time of day.

**Comment by daphnei** [comment]
Wouldn't it be a ManyToOne relationship, not a ManyToMany? Each Annotation has some number of TimeStamps associated with it, but every TimeStamp is associated with a single Annotation.

**Comment by kirubarajan** [comment]
Implemented requested changes.

**Pull request merged**
